-- Active: 1775506739659@@localhost@5432@displayflex
INSERT INTO
    poids (
        marketing,
        design_graphique,
        programmation,
        ecriture,
        design_interface,
        data,
        media,
        maths,
        english,
        economie,
        leadership,
        communication_orale,
        creativite,
        pensee_analytique,
        gestion_projet,
        storytelling
    )
VALUES (
        7,
        3,
        14,
        11,
        5,
        20,
        3,
        17,
        13,
        10,
        6,
        12,
        0,
        20,
        0,
        0
    ), -- 1: Data Analyst
    (
        10,
        18,
        11,
        7,
        19,
        8,
        9,
        4,
        11,
        5,
        5,
        11,
        18,
        12,
        0,
        10
    ), -- 2: Web Designer
    (
        18,
        6,
        2,
        19,
        6,
        7,
        18,
        5,
        17,
        11,
        10,
        19,
        15,
        0,
        14,
        19
    ), -- 3: Communication Specialist
    (
        20,
        7,
        3,
        14,
        7,
        16,
        8,
        12,
        17,
        18,
        18,
        16,
        15,
        17,
        19,
        14
    ), -- 4: Marketing Manager
    (
        9,
        14,
        7,
        10,
        20,
        13,
        9,
        6,
        13,
        8,
        8,
        15,
        18,
        16,
        11,
        13
    ), -- 5: UX/UI Designer
    (
        5,
        4,
        20,
        8,
        10,
        11,
        7,
        12,
        13,
        6,
        7,
        0,
        12,
        19,
        0,
        0
    ), -- 6: Web Developer
    (
        8,
        20,
        4,
        6,
        9,
        4,
        17,
        7,
        10,
        5,
        5,
        0,
        20,
        0,
        9,
        18
    ), -- 7: Motion Designer
    (
        11,
        20,
        3,
        7,
        11,
        4,
        15,
        5,
        11,
        7,
        6,
        12,
        20,
        0,
        12,
        16
    ), -- 8: Graphic Designer
    (
        17,
        5,
        4,
        20,
        9,
        14,
        15,
        7,
        18,
        11,
        9,
        15,
        16,
        17,
        16,
        20
    ), -- 9: Content Strategist
    (
        15,
        4,
        8,
        14,
        11,
        16,
        8,
        13,
        15,
        18,
        19,
        17,
        14,
        18,
        20,
        16
    ), -- 10: Product Manager
    (
        18,
        17,
        2,
        14,
        10,
        9,
        17,
        6,
        16,
        15,
        20,
        18,
        20,
        13,
        17,
        19
    ), -- 11: Creative Director
    (
        19,
        4,
        12,
        15,
        11,
        18,
        12,
        11,
        17,
        10,
        0,
        14,
        13,
        19,
        15,
        0
    ), -- 12: SEO Specialist
    (
        4,
        3,
        20,
        9,
        12,
        17,
        7,
        14,
        14,
        7,
        10,
        0,
        13,
        19,
        0,
        0
    ), -- 13: Full Stack Developer
    (
        18,
        8,
        3,
        16,
        7,
        11,
        19,
        4,
        16,
        8,
        9,
        18,
        17,
        11,
        14,
        17
    ), -- 14: Community manager,
    (
        12,
        7,
        2,
        20,
        6,
        9,
        16,
        3,
        17,
        10,
        15,
        16,
        16,
        14,
        18,
        19
    ), -- 15: Responsable éditorial,
    (
        9,
        16,
        6,
        11,
        8,
        5,
        20,
        8,
        12,
        6,
        6,
        11,
        19,
        10,
        12,
        18
    ), -- 16: Vidéaste / créateur vidéo,
    (
        10,
        6,
        5,
        14,
        7,
        9,
        18,
        6,
        15,
        8,
        10,
        16,
        16,
        12,
        17,
        19
    ), -- 17: Podcast producer,
    (
        3,
        2,
        19,
        7,
        8,
        14,
        4,
        13,
        15,
        7,
        11,
        12,
        11,
        18,
        15,
        3
    ), -- 18: DevOps,
    (
        5,
        4,
        14,
        17,
        9,
        13,
        6,
        11,
        18,
        7,
        7,
        13,
        15,
        19,
        9,
        11
    ), -- 19: Prompt engineer,
    (
        5,
        8,
        20,
        7,
        16,
        8,
        6,
        9,
        13,
        5,
        6,
        9,
        14,
        17,
        8,
        4
    ), -- 20: Développeur front-end,
    (
        3,
        2,
        20,
        6,
        7,
        15,
        4,
        13,
        13,
        6,
        7,
        8,
        9,
        19,
        9,
        2
    ), -- 21: Développeur back-end,
    (
        5,
        4,
        20,
        8,
        10,
        11,
        7,
        12,
        13,
        6,
        7,
        10,
        12,
        19,
        9,
        4
    ), -- 22: Développeur web,
    (
        4,
        3,
        18,
        9,
        10,
        13,
        5,
        15,
        16,
        11,
        14,
        13,
        11,
        20,
        17,
        5
    ), -- 23: Architecte logiciel,
    (
        17,
        13,
        2,
        18,
        9,
        12,
        20,
        4,
        15,
        12,
        11,
        19,
        19,
        10,
        13,
        20
    ), -- 24: Influenceur,
    (
        18,
        4,
        6,
        11,
        9,
        18,
        10,
        10,
        14,
        16,
        13,
        15,
        12,
        19,
        18,
        11
    ), -- 25: Responsable CRM,
    (
        20,
        6,
        5,
        13,
        9,
        16,
        13,
        9,
        15,
        14,
        9,
        14,
        14,
        18,
        14,
        12
    ), -- 26: Webmarketer,
    (
        17,
        9,
        3,
        17,
        8,
        10,
        17,
        5,
        16,
        10,
        9,
        17,
        16,
        11,
        15,
        18
    ), -- 27: Chargé de communication digitale,
    (
        20,
        7,
        4,
        14,
        8,
        17,
        12,
        11,
        16,
        18,
        17,
        16,
        15,
        18,
        19,
        13
    ), -- 28: Responsable marketing digital,
    (
        8,
        16,
        6,
        10,
        20,
        12,
        8,
        7,
        14,
        9,
        9,
        16,
        19,
        17,
        12,
        13
    ), -- 29: Product designer,
    (
        6,
        14,
        10,
        12,
        15,
        7,
        13,
        10,
        12,
        8,
        8,
        12,
        20,
        17,
        14,
        18
    ), -- 30: Game designer,
    (
        14,
        4,
        7,
        14,
        12,
        15,
        7,
        11,
        15,
        17,
        16,
        18,
        13,
        18,
        19,
        15
    ), -- 31: Product owner,
    (
        16,
        7,
        5,
        12,
        10,
        12,
        11,
        9,
        15,
        13,
        16,
        17,
        14,
        15,
        20,
        14
    ), -- 32: Chef de projet digital,
    (
        19,
        8,
        6,
        11,
        11,
        16,
        11,
        10,
        14,
        18,
        14,
        15,
        14,
        16,
        17,
        12
    ), -- 33: Responsable e-commerce,
    (
        15,
        5,
        8,
        13,
        9,
        15,
        10,
        11,
        16,
        19,
        19,
        18,
        13,
        18,
        20,
        15
    );
-- 34: Responsable transformation digitale;

INSERT INTO
    metiers (nom, description, id_poids)
VALUES (
        'Data Analyst',
        'Collecte, nettoie et analyse des données pour dégager des insights, construit tableaux de bord et rapports, formule des recommandations métier basées sur les indicateurs clés pour aider à la décision.',
        1
    ),
    (
        'Web Designer',
        'Crée l''identité visuelle et la mise en page de sites web, définit la charte graphique digitale, conçoit maquettes responsives et éléments graphiques en veillant à la cohérence de marque et à l''accessibilité.',
        2
    ),
    (
        'Communication Specialist',
        'Conçoit et met en œuvre des stratégies de communication 360° (médias, réseaux sociaux, événements, RP), rédige contenus et messages clés, gère la relation avec les parties prenantes et suit la réputation de la marque.',
        3
    ),
    (
        'Marketing Manager',
        'Pilote les stratégies marketing digitales (SEO/SEA, e-mail, réseaux sociaux, display), planifie et exécute les campagnes, suit les KPIs, optimise les budgets médias et coordonne agences et équipes internes.',
        4
    ),
    (
        'UX/UI Designer',
        'Conçoit des expériences et interfaces centrées utilisateur, mène la recherche UX, crée wireframes, prototypes et maquettes UI, puis teste et itère les parcours pour améliorer l''ergonomie sur web et mobile.',
        5
    ),
    (
        'Web Developer',
        'Développe et maintient des sites et applications web, écrit du code propre et testable (front et/ou back), intègre maquettes, optimise les performances et corrige les bugs en collaboration avec les designers et chefs de projet.',
        6
    ),
    (
        'Motion Designer',
        'Crée des animations 2D/3D et visuels en mouvement pour le web, la publicité ou le produit, participe à la conception créative, prépare storyboards et moodboards, puis anime typographie, illustration et vidéo.',
        7
    ),
    (
        'Graphic Designer',
        'Conçoit des identités visuelles et supports print/digitaux (logos, affiches, bannières, interfaces), met en forme messages et concepts de marque en images claires et impactantes, en respectant charte et contraintes techniques.',
        8
    ),
    (
        'Content Strategist',
        'Définit la stratégie éditoriale multicanale, planifie et coordonne la production de contenus, structure les messages selon les objectifs business et SEO, mesure la performance et ajuste les formats et sujets.',
        9
    ),
    (
        'Product Manager',
        'Porter la vision du produit, analyser besoins utilisateurs et marché, prioriser la roadmap, rédiger user stories et coordonner équipes design, tech et business pour livrer des fonctionnalités à forte valeur.',
        10
    ),
    (
        'Creative Director',
        'Définit la vision créative globale d''une marque ou d''un projet, supervise les concepts visuels et narratifs, encadre les équipes créatives, valide les pistes et garantit la cohérence esthétique et stratégique.',
        11
    ),
    (
        'SEO Specialist',
        'Optimise la visibilité d''un site sur les moteurs de recherche via audit technique, recherche de mots-clés, optimisation on-page, netlinking et analyse de performances pour augmenter trafic organique qualifié.',
        12
    ),
    (
        'Full-Stack Developer',
        'Développe le front-end et le back-end d''applications web, conçoit APIs et modèles de données, intègre interfaces, gère la logique serveur et veille à la performance, la sécurité et la maintenabilité de l''ensemble.',
        13
    ),
    (
        'Community manager',
        'Anime et fédère une communauté en ligne autour d''une marque, crée et publie du contenu engageant, modère les interactions, analyse les performances, répond aux commentaires et critiques, et développe des campagnes pour renforcer l''engagement et la fidélité.',
        14
    ),
    (
        'Responsable éditorial',
        'Définit la ligne éditoriale, coordonne la production de contenus multimédias, manage les équipes d''éditeurs et rédacteurs, pilote le planning éditorial, veille à la qualité et à la cohérence des messages, et gère les budgets et délais de publication.',
        15
    ),
    (
        'Vidéaste / créateur vidéo',
        'Conçoit et produit des vidéos de la prise de vue au montage, maîtrise les techniques audiovisuelles et les logiciels de montage (Premiere, After Effects), crée des scénarios captivants, ajuste le son et l''image, et optimise le contenu pour différentes plateformes.',
        16
    ),
    (
        'Podcast producer',
        'Planifie et coordonne la production de podcasts, gère l''enregistrement et l''édition audio, maîtrise les outils de montage sonore, coordonne invités et timeline, développe une stratégie de contenu, et assure la diffusion sur les plateformes adaptées.',
        17
    ),
    (
        'DevOps',
        'Automatise et optimise les processus de développement et de déploiement, maîtrise CI/CD (Jenkins, GitLab), gère l''infrastructure cloud (AWS, Azure), script en Python ou Bash, surveille les performances, assure la sécurité et la fiabilité des systèmes.',
        18
    ),
    (
        'Prompt engineer',
        'Conçoit et optimise des prompts pour guider les modèles d''IA génératifs, teste et itère les instructions pour améliorer la pertinence des réponses, comprend les modèles de langage (LLM, NLP), maîtrise Python, et évalue la qualité des outputs IA.',
        19
    ),
    (
        'Développeur front-end',
        'Développe les interfaces utilisateur de sites et applications web, maîtrise HTML, CSS, JavaScript et frameworks modernes (React, Vue, Angular), assure le responsive design, optimise les performances front, et collabore avec les designers UX/UI.',
        20
    ),
    (
        'Développeur back-end',
        'Conçoit et maintient la logique serveur, les APIs et les bases de données, maîtrise les langages back (PHP, Python, Node.js, Java), gère la sécurité, les accès et la sauvegarde des données, et assure la scalabilité et la performance des systèmes.',
        21
    ),
    (
        'Développeur web',
        'Développe et maintient des sites et applications web, écrit du code propre et testable (front et/ou back), intègre maquettes, optimise les performances et corrige les bugs en collaboration avec les designers et chefs de projet.',
        22
    ),
    (
        'Architecte logiciel',
        'Conçoit l''architecture technique d''applications complexes, définit les choix technologiques et normes de sécurité, maîtrise systèmes d''exploitation, langages (Java, Python, C++), protocoles réseaux, et pilote les projets techniques en lien avec les équipes.',
        23
    ),
    (
        'Influenceur',
        'Crée du contenu engageant sur les réseaux sociaux, développe et anime sa communauté, collabore avec des marques pour des partenariats, analyse les données d''engagement, maîtrise le storytelling et le copywriting, et inspire confiance par son charisme.',
        24
    ),
    (
        'Responsable CRM',
        'Pilote la stratégie de relation client, maîtrise les outils CRM (Salesforce, HubSpot), conçoit et suit les campagnes d''emailing et d''automation, analyse les données clients pour optimiser la fidélisation, et coordonne les équipes marketing, vente et support.',
        25
    ),
    (
        'Webmarketer',
        'Déploie des stratégies marketing digital (SEO, SEA, réseaux sociaux, display), analyse le trafic et les conversions avec Google Analytics, optimise les campagnes, crée du contenu adapté aux canaux digitaux, et mesure le ROI pour améliorer les performances.',
        26
    ),
    (
        'Chargé de communication digitale',
        'Conçoit et met en œuvre la stratégie de communication digitale, rédige et publie des contenus pour le web et les réseaux sociaux, gère la e-réputation, coordonne les campagnes online, et analyse les KPIs pour ajuster les actions.',
        27
    ),
    (
        'Responsable marketing digital',
        'Définit et pilote la stratégie marketing digitale globale, coordonne les campagnes multicanales (SEO/SEA, social ads, emailing), manage les équipes et budgets, analyse les performances et le ROI, et aligne les actions digitales avec les objectifs business.',
        28
    ),
    (
        'Product designer',
        'Conçoit l''expérience et l''interface de produits digitaux de bout en bout, mène recherches utilisateurs et tests d''usabilité, crée wireframes, prototypes et maquettes, collabore avec les équipes produit et tech, et assure la cohérence visuelle et fonctionnelle.',
        29
    ),
    (
        'Game designer',
        'Conçoit les mécaniques, règles et univers de jeux vidéo, rédige le cahier des charges et le game design document, teste et équilibre le gameplay, maîtrise les outils (Unity, Unreal) et logiciels 3D, et collabore avec développeurs et artistes.',
        30
    ),
    (
        'Product owner',
        'Définit et priorise le backlog produit en méthode Agile/Scrum, traduit la vision produit en user stories, valide les livrables de chaque sprint, coordonne équipe de développement et parties prenantes, et maximise la valeur livrée à chaque itération.',
        31
    ),
    (
        'Chef de projet digital',
        'Pilote des projets digitaux de la conception à la livraison, coordonne les équipes techniques, créatives et métier, gère planning, budget et risques, assure la communication avec les parties prenantes, et veille à la qualité et au respect des délais.',
        32
    ),
    (
        'Responsable e-commerce',
        'Pilote la stratégie et les opérations d''un site e-commerce, optimise le tunnel de conversion et l''expérience client, analyse les KPIs (taux de conversion, panier moyen), coordonne marketing, logistique et tech, et mène la veille concurrentielle.',
        33
    ),
    (
        'Responsable transformation digitale',
        'Accompagne l''organisation dans sa mutation numérique, définit la vision et la feuille de route digitale, forme les équipes aux nouveaux outils et méthodes, pilote le change management, cartographie les compétences, et mesure l''adoption des transformations.',
        34
    );